version: '3'
services:
  redis-server:
    command: redis-server --appendonly yes
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
  unibot:
    image: 'kvoli/unibot'
    env_file:
      - prod.env
  watchtower:
    command: "unibot"
    container_name: watchtower
    image: containrrr/watchtower:latest
    env_file:
      - watchtower.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
