version: '3'
services:
  redis-server:
    image: 'redis'
    container_name: redis-server
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
  unibot-canvas:
    image: 'kvoli/unibot-canvas'
    container_name: unibot-canvas
    restart: always
    env_file:
      - prod.env
    build: "canvas/"
    links:
      - "redis-server:redis"
    depends_on: 
      - "redis-server"
      - "unibot-disco"
  unibot-disco:
    image: 'kvoli/unibot-disco'
    container_name: unibot-disco
    restart: always
    env_file:
      - prod.env
    build: "bot/"
    links:
      - "redis-server:redis"
    depends_on: 
      - "redis-server"
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    command: unibot-disco unibot-canvas
    env_file:
      - watchtower.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
