name: Package docker

on: [push]

jobs:
  build-core:
    name: build and push web image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build -t kvoli/unibot .
      - name: Push the Docker image to the registry
        run: docker push kvoli/unibot:latest
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            details: Published latest image of unibot to dockerhub.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
